Add support for built-in regex with Azure SQL DB
efcore/EFCore.CheckConstraints pull request #164
Opened 2024-05-27 10:38 UTC by ErikEJ

fixes #156

@roji

2024-05-27 11:08 UTC, ErikEJ commented
Verified on my activated server with:

```sql
CREATE TABLE Emails
(
ID int,
Email nvarchar(500) CONSTRAINT CK_Email CHECK (REGEXP_LIKE (Email, '^[^@]+@[^@]+$')),
)

INSERT INTO Emails VALUES (1, 'exy')

INSERT INTO Emails VALUES (2, 'ex@y')

```

2024-06-17 08:11 UTC, ErikEJ commented
@roji Thoughts?

2025-01-02 20:06 UTC, ErikEJ commented
@roji Possible to have this reviewed?

2025-02-26 17:01 UTC, ErikEJ commented
@roji  RegEx on Azure is now in public preview - possible to get this out as a preview?

2025-05-12 06:19 UTC, ErikEJ commented
@roji Any chance to get this out as a preview package?

2025-05-24 08:44 UTC, roji commented
Hey Eric, sorry for the super long silence on this - I'm slowly coming back to a more normal mode after the pre-Build craziness and the work on the Microsoft.Extensions.VectorData. I'm working through my backlog - will  try to look at this soon.

2025-06-10 04:29 UTC, ErikEJ commented
@roji - thanks, yes  things have changed since I created this PR more than a year ago.

2025-06-10 05:48 UTC, ErikEJ commented
@roji PR updated

2025-06-10 07:17 UTC, ErikEJ commented on EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs
> +                if (sqlServerOptionsExtension.GetType()?.GetProperty($"{engineType}CompatibilityLevel")?.GetValue(sqlServerOptionsExtension) is int compatibilityLevel
We do not reference the SQL Server provider, so how would I do this without reflection?

2025-06-10 10:14 UTC, roji commented on EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs
> +                if (sqlServerOptionsExtension.GetType()?.GetProperty($"{engineType}CompatibilityLevel")?.GetValue(sqlServerOptionsExtension) is int compatibilityLevel
You're right, I forgot that this plugin doesn't reference any providers (it has been a while since I've been here...).

2025-06-10 10:40 UTC, ErikEJ commented
@roji Verdict?

2025-06-10 13:29 UTC, roji requested changes
Looks pretty good! See mainly nits.

2025-06-10 13:29 UTC, roji commented on EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs
> +            if (engineType != null && (engineType.ToString() == "SqlServer" || engineType.ToString() == "AzureSql"))
nit:

```suggestion
            if (engineType?.ToString() is "SqlServer" or "AzureSql")
```

2025-06-10 13:29 UTC, roji commented on EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs
> +                if (sqlServerOptionsExtension.GetType()?.GetProperty($"{engineType}CompatibilityLevel")?.GetValue(sqlServerOptionsExtension) is int compatibilityLevel
nit:

```suggestion
                if (sqlServerOptionsExtension.GetType()?.GetProperty($"{engineType}CompatibilityLevel")?.GetValue(sqlServerOptionsExtension) is >= 170)
```

2025-06-10 13:29 UTC, roji commented on EFCore.CheckConstraints/Internal/ValidationCheckConstraintConvention.cs
> +        var sqlServerOptionsExtension  = _dbContextOptions.Extensions
Rather than doing this each time for each regex, maybe do this once at initialization time and cache a simple `_isSqlServerWithNewRegex` or similar?

2025-06-10 13:42 UTC, ErikEJ commented
@roji Nits addressed 😄

2025-06-10 13:45 UTC, roji approved these changes
Thanks @ErikEJ - one final nit and I'll merge.

2025-06-10 14:13 UTC, merged

2025-06-10 14:14 UTC, roji commented
Thanks @ErikEJ!

2025-06-10 14:39 UTC, ErikEJ commented
@roji OK if I publish 9.1.0 ?

2025-06-10 15:56 UTC, roji commented
Sure, go ahead!