Constraint added for validating StringLengthAttribute.MinimumLength.
efcore/EFCore.CheckConstraints pull request #21
Opened 2021-02-23 00:15 UTC by SetTrend

Currently, `EFCore.CheckConstraints` lacks an option to validate the [`StringLengthAttribute.MinimumLength`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.stringlengthattribute.minimumlength) data annotation attribute property.

The [`StringLengthAttribute`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.stringlengthattribute) combines both, [`MinLengthAttribute`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.minlengthattribute) and [`MaxLengthAttribute`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.maxlengthattribute) attributes. While the [`StringLengthAttribute.MaximumLength`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.stringlengthattribute.maximumlength) property is validated by Entity Framework (Core), it lacks validating the corresponding [`StringLengthAttribute.MinimumLength`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.stringlengthattribute.minimumlength) property.

This pull requests adds validation and constraint creation for the [`StringLengthAttribute.MinimumLength`](https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.stringlengthattribute.minimumlength) property.

2021-03-04 17:57 UTC, roji requested changes
Thanks for this PR and sorry it took me a while to respond.

Overall this looks good. A couple of points:
* [StringLength] also defines the maximum length, not just the minimum - this should also be applied as a check constraint. For example, in the README.md changes you're proposing, I'd expect to have `LENGTH("Required") <= 100`.
    * If both minimum and maximum are provided, both should be implemented in the same check constraint (and not two constraints).
* While providing the maximum length seems to be mandatory for the attribute, the minimum is optional. If the minimum isn't specified (i.e. it's zero), we should generate a check in the constraint for that.

2021-03-05 13:54 UTC, SetTrend commented
Hello, @roji, thank you for your comment.

Actually, `[StringLength(MaximumLength=...)]` is already dealt with by EF intrinsically: It's the length of the column.

So, `[StringLength(MaximumLength=100)]` (or `[StringLength(100)]`, resp.) yields `VARCHAR(100)`.
<br/>

```c#
[StringLength(100, MinimumLength = 1)]
public string Required;
```
yields
```sql
Required VARCHAR(100) CONSTRAINT CK_Required_MinLength CHECK Required >=1
```

2021-03-05 14:55 UTC, roji commented
You're right, that makes sense - IIRC that's the reason I never implemented support for it in the first place (missing that it had a minimal option too).

2021-03-05 14:57 UTC, roji approved these changes

2021-03-05 14:57 UTC, merged

2023-02-24 12:59 UTC, glen-84 commented
Actually that's only true for VARCHAR columns, TEXT columns cannot be constrained with a max length without using a CHECK constraint.

2023-02-24 13:16 UTC, roji commented
@glen-84 when a max length is specified, the EF provider automatically select TEXT vs. VARCHAR based on whether a max length is defined or not. I don't think it makes much sense to require a TEXT column with a max length enforced by a check constraint, when you can just have a VARCHAR(x) column instead...

2023-02-24 13:35 UTC, glen-84 commented
@roji VARCHAR is limited to 65,535 characters in MySQL.

2023-02-24 17:43 UTC, roji commented
OK, but doesn't the MySQL provider still interpret the maxlength component of StringLengthAttribute, making the column a varchar?

I'm not sure what we can do here - AFAIK it's undesirable for most providers to set up a check constraint for the string max length, because that's already interpreted by the provider itself. There's no way we can know in this plugin about the specific provider behavior around this...

2023-02-24 18:42 UTC, glen-84 commented
> OK, but doesn't the MySQL provider still interpret the maxlength component of StringLengthAttribute, making the column a varchar?

We're actually using fluent configuration, not data annotations, so this library will likely not help us.

When using `HasMaxLength`, the provider will use a `longtext` type for any length above 16,388.

- I have no idea why it's this number -- if it's 4 bytes per character, then it should surely be 65,535 / 4 = ~16,383.
    - This might be a typo [here](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/27f227388a5e1b68292f6c649227bdf0637598d7/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L386)? 553 instead of 535.
- I also don't know why it uses `longtext` and not `mediumtext`. Do providers need to align with SQL-standard types?

So, if you want a string to have a max length of, say, 20,000, then it'll get the `longtext` type, and you'll be able to insert values with a length of ~1,073,741,823. It's unconstrained.

> I'm not sure what we can do here - AFAIK it's undesirable for most providers to set up a check constraint for the string max length

If you have access to the column type, you can use that information to apply a max length check constraint for specific column types (f.e. text, mediumtext, longtext), depending on the provider.

If you only have access to the CLR type, then it might be a bit more awkward, and require you to determine the column type based on the CLR type + max length + provider.

We're probably going to do something similar, and also add a `HasMinLength` extension method, like this:

```cs
    public static PropertyBuilder<TProperty> HasMinLength<TProperty>(
        this PropertyBuilder<TProperty> builder,
        int minLength)
    {
        builder.Metadata.AddAnnotation("MinimumLength", minLength);

        return builder;
    }
```

We'll use this metadata to apply minimum length check constraints.

2023-02-24 20:49 UTC, roji commented
@glen-84 you probably want to raise all the MySQL-specific questions on the MySQL repro - each provider does its thing based on what the database supports. Database textual types in particular are quite different across databases and generally have some rough edges. PG is pretty nice/consistent - you can have varchar(x) for any maximum length, or otherwise just use text for any size (without any perf difference between the two).

> If you have access to the column type, you can use that information to apply a max length check constraint for specific column types (f.e. text, mediumtext, longtext), depending on the provider.

This plugin doesn't generally do per-provider checks - that wouldn't be a very scalable approach. Maybe it's reasonable to just check if the store type has a length facet (i.e. are there parenthese in there, indicating a maximum length) - feel free to open an issue for doing that. Honestly, there hasn't been enough interest in this particular thing so far.